version: '3.8'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-portal
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=hospital_portal
      - PGPORT=5432
    networks:
      - hospital-network
    restart: unless-stopped

  postgres:
    image: postgres:13-alpine
    container_name: hospital-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hospital_portal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hospital-network
    restart: unless-stopped

networks:
  hospital-network:
    driver: bridge

volumes:
  postgres-data:
